### PR TITLE
Read the docs

### PR DESCRIPTION
**Pull request by HomerReid**
Created mkdocs-style documentation tree in `doc` subdirectory of main repository.

### CODE REVIEW

**Comment by oskooi** [comment]
A beta version of this documentation is available on [ReadTheDocs](http://mpbbeta.readthedocs.io/en/latest/MPB/).

**Comment by stevengj** [comment]
Thanks!  Travis failure on osx should be fixed by 0dbd4c2576459312b197ce34bda517cbfaee81bc

**Comment by stevengj** [comment]
I've enabled this on readthedocs for stevengj.

**Comment by stevengj** [comment]
Why doesn't http://mpb.readthedocs.io/en/latest/ or http://meep.readthedocs.io/en/latest/ work?

**Comment by HomerReid** [comment]
Both sites are working fine: 

http://mpbbeta.readthedocs.io/en/latest/MPB/
http://meep.readthedocs.io/en/latest/Meep

**Pull request merged**
