### PR TITLE
Add scheme interface for maxwell_dominant_planewave

### PR DESCRIPTION
**Pull request by ChristopherHogan**
* Run `check.ctl` tests with MPI if available
* Add `get_dominant_planewave` as scheme interface to `maxwell_dominant_planewave`

I verified that `get-dominant-planewave` is callable from guile, but I'm not verifying the results yet. Could you tell me the expected dominant planewave for the "Square lattice of dielectric rods in air" test case for bands 1-8?
@stevengj @oskooi

### CODE REVIEW

**Comment by stevengj** [comment]
For a test, you could just do a 1d cell with period 1, filled with air (the default), at kx=0.4, and the results should be the same as in maxwell_test.c

**Comment by ChristopherHogan** [comment]
I wrote the following test for this:
```scheme
(set! geometry '())
(set! k-points (list (vector3 0.4 0 0)))
(set! geometry-lattice (make lattice (size 10 1 no-size)))
(set! num-bands 8)
(run-te)
(check-almost-equal (list (vector-ref (get-dominant-planewave 1) 0)
                          (vector-ref (get-dominant-planewave 2) 0)
                          (vector-ref (get-dominant-planewave 3) 0))
                    (list 0.4 -0.6 1.4))
```
However, instead of the expected
```
0.4
-0.6
1.4
```
I'm getting
```
0.04
-0.06
0.14
```
Is there a parameter I have to change to get the same results as
```
maxwell_test -1 -c 1e-9 -x 256 -E 1e-3 -e -k 0.4 -n 1
```

**Comment by stevengj** [comment]
Just change the cell size to 1 by 0.1 and increase the resolution to 100

**Comment by ChristopherHogan** [comment]
Updated the test. This should be ready.

**Pull request merged**
